---
- name: initial deployment check
  shell: "echo 'bootstrapped' > /etc/ceph-install"
  register: newhost
  args:
    creates: "/etc/ceph-install"

- name: install packages
  apt:
    name:
      - ceph-osd
      - ceph-mds
      - ceph-mon
      - ceph-mgr
      - radosgw
      - libjemalloc2
    state: latest

- name: install sysctl tweaks
  template:
    src: ceph/sysctl.conf.j2
    dest: /etc/sysctl.d/pvc-ceph.conf

- name: activate sysctl tweaks
  command: sysctl -p /etc/sysctl.d/pvc-ceph.conf

- name: install user limits overrides
  template:
    src: ceph/limits.conf.j2
    dest: /etc/security/limits.d/99-pvc-ceph.conf

- name: install ceph default config
  template:
    src: ceph/default.conf.j2
    dest: /etc/default/ceph

- name: create ceph configuration directory
  file:
    dest: /etc/ceph
    state: directory

- include: add_cluster_ips.yml
  when: newhost.changed

- include: bootstrap_ceph.yml
  when: newhost.changed
