---
- name: install libvirt packages
  apt:
    name:
      - libvirt-daemon-system
      - qemu-kvm
      - qemu-utils
      - qemu-block-extra
      - vhostmd
      - ceph-common
      - libjemalloc2
    state: latest

- name: install libvirt configuration
  template:
    src: libvirt/{{ item }}.j2
    dest: /etc/libvirt/{{ item }}
  with_items:
    - libvirtd.conf
    - ceph-secret.xml
  notify: restart libvirtd

- name: define ceph secret
  command: virsh secret-define /etc/libvirt/ceph-secret.xml
  ignore_errors: true

- name: set ceph secret value
  command: virsh secret-set-value --secret {{ ceph_storage_secret_uuid }} --base64 {{ ceph_storage_secret_key }}
  ignore_errors: true

- name: configure libvirt for listening
  replace:
    dest: /etc/default/libvirtd
    regexp: '#libvirtd_opts=""'
    replace: 'libvirtd_opts="--listen"'
  notify: restart libvirtd

- name: disable services
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - libvirtd
