---

# Set this_node fact
- set_fact:
    this_node: "{{ inventory_hostname.split('.')[0] }}"
  tags: always

# Set coordinator state fact
- set_fact:
    is_coordinator: "{% for node in pvc_nodes if node.hostname == this_node %}{{ node.is_coordinator }}{% endfor %}"
  tags: always

# First-run check
- name: check if this is a new instance
  shell: "echo 'bootstrapped' > /etc/pvc-install.pvc"
  args:
    creates: /etc/pvc-install.pvc
  register: newhost_check
  tags: always

- name: set newhost fact
  set_fact:
    newhost: yes
  when: newhost_check.changed
  tags: always

- include_tasks: common/add_cluster_ips.yml
  when: newhost is defined and newhost
  tags: always

# Install system tweaks
- include_tasks: system/main.yml
  tags: pvc-system

# Install base databases (coordinators only)
- include_tasks: ceph/main.yml
  tags: pvc-ceph
  when: is_coordinator

- include_tasks: zookeeper/main.yml
  tags: pvc-zookeeper
  when: is_coordinator

- include_tasks: patroni/main.yml
  tags: pvc-patroni
  when: is_coordinator

- include_tasks: keydb/main.yml
  tags: pvc-keydb
  when: is_coordinator

# Install core services
- include_tasks: libvirt/main.yml
  tags: pvc-libvirt

- include_tasks: frr/main.yml
  tags: pvc-frr

# Install PVC daemon
- include_tasks: pvc/main.yml
  tags: pvc-daemon

# Install PVC autobackup
- include_tasks: autobackup/main.yml
  tags: pvc-autobackup
  when: pvc_autobackup is defined

# Install PVC automirror
- include_tasks: automirror/main.yml
  tags: pvc-automirror
  when: pvc_automirror is defined

# Install CPU tuning
- include_tasks: cputuning/main.yml
  tags: pvc-cputuning
  when: debian_version|int >= 11 and cpu_tuning is defined

- name: restart server on first install
  reboot:
    post_reboot_delay: 60
    reboot_timeout: 1800
  when: newhost is defined and newhost
  tags: always
