---
- name: add module blacklist
  template:
    src: system/blacklist.j2
    dest: /etc/modprobe.d/blacklist.conf

- include: ceph.yml
  tags: pvc-ceph

- include: zookeeper.yml
  tags: pvc-zookeeper

- include: libvirt.yml
  tags: pvc-libvirt

- include: frr.yml
  tags: pvc-frr

- include: patroni.yml
  tags: pvc-patroni

- include: pvc.yml
  tags: pvc-pvc
  run_once: true
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
