---
- name: install pvc packages
  apt:
    name:
      - pvc-daemon-node
      - pvc-daemon-health
      - pvc-daemon-worker
      - pvc-daemon-api
      - pvc-daemon-common
      - pvc-client-cli
      - ethtool
      - jq
      # default provisioner script helper programs
      - debootstrap
      - rinse
    state: present
  register: apt_res
  retries: 5
  until: apt_res is success

- name: install pvc daemon configuration
  template:
    src: pvc/{{ item }}.j2
    dest: /etc/pvc/{{ item }}
    mode: 0640
  with_items:
    - pvc.conf

- name: remove obsolete pvc daemon configurations
  file:
    dest: "/etc/pvc/{{ item }}"
    state: absent
  with_items:
    - pvcnoded.yaml
    - pvcapid.yaml
    - autobackup.yaml

- name: install API SSL certificate file
  copy:
    content: "{{ pvc_api_ssl_cert }}"
    dest: /etc/pvc/api-cert.pem
    mode: 0644
  no_log: True
  when: pvc_api_enable_ssl and not pvc_api_ssl_cert_path

- name: install API SSL key file
  copy:
    content: "{{ pvc_api_ssl_key }}"
    dest: /etc/pvc/api-key.pem
    mode: 0640
  no_log: True
  when: pvc_api_enable_ssl and not pvc_api_ssl_key_path

- name: install check_mk agent check
  template:
    src: pvc/pvc_status.j2
    dest: /usr/lib/check_mk_agent/plugins/pvc_status
    mode: 0755

- include: pvc/bootstrap.yml
  run_once: yes
  when: do_bootstrap is defined and do_bootstrap and is_coordinator

- meta: flush_handlers

- name: ensure services are started and running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - pvcnoded
  when: newhost is defined and newhost
