---
- name: install pvc packages
  apt:
    name:
      - pvc-daemon
      - pvc-client-cli
      - pvc-client-common
      - debootstrap
      - ethtool
    state: latest

- name: install pvc configuration
  template:
    src: pvc/{{ item }}.j2
    dest: /etc/pvc/{{ item }}
  with_items:
    - pvcd.yaml
  notify: restart pvcd

- name: stop and disable unneccessary services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - pdns.service

- include: pvc/bootstrap.yml
  when: bootstrap is defined and bootstrap
  run_once: yes

- name: enable services but don't start them
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - pvc-flush.service
    - pvcd.service
    - pvcd.target

- meta: flush_handlers
