---
- name: install pvc packages
  apt:
    name:
      - pvc-daemon
      - pvc-client-common
      - pvc-client-cli
      - pvc-client-api
      - debootstrap
      - ethtool
    state: latest

- name: install pvc configurations
  template:
    src: pvc/{{ item }}.yaml.j2
    dest: /etc/pvc/{{ item }}.yaml
  notify:
    - restart {{ item }}
  with_items:
    - pvcd
    - pvc-api

- name: stop and disable unneccessary services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - pdns.service

- include: pvc/bootstrap.yml
  when: bootstrap is defined and bootstrap
  run_once: yes

- name: enable daemon services but don't start them
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - pvc-flush.service
    - pvcd.service
    - pvcd.target

- meta: flush_handlers
