---
- name: install pvc packages
  apt:
    name:
      - pvc-daemon-node
      - pvc-daemon-api
      - pvc-daemon-common
      - pvc-client-cli
      - debootstrap
      - ethtool
      - jq
    state: latest

- name: install pvc configurations
  template:
    src: pvc/{{ item }}.j2
    dest: /etc/pvc/{{ item }}
  notify:
    - restart pvcnoded
  with_items:
    - pvcnoded.yaml
    - pvcapid.yaml

- name: install API SSL certificate file
  copy:
    content: "{{ pvc_api_ssl_cert }}"
    dest: /etc/pvc/api-cert.pem
    mode: 0644
  no_log: True
  when: pvc_api_enable_ssl and not pvc_api_ssl_cert_path

- name: install API SSL key file
  copy:
    content: "{{ pvc_api_ssl_key }}"
    dest: /etc/pvc/api-key.pem
    mode: 0640
  no_log: True
  when: pvc_api_enable_ssl and not pvc_api_ssl_key_path

- name: stop and disable unneccessary services
  service:
    name: "{{item }}"
    state: stopped
    enabled: no
  with_items:
    - pdns.service
    - dnsmasq.service

- include: pvc/bootstrap.yml
  run_once: yes
  when: bootstrap is defined and bootstrap and is_coordinator

- name: enable daemon services but don't start them
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - pvc-flush.service
    - pvcnoded.service
    - pvc.target

- name: install daily vacuum script
  template:
    src: pvc/pvc-vacuum.j2
    dest: /etc/cron.daily/pvc-vacuum
    mode: 0755

- meta: flush_handlers
