---

- name: remove cpu tuning configurations
  file:
    dest: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/system.slice
    - /etc/systemd/system/user.slice
    - /etc/systemd/system/osd.slice
    - /etc/systemd/system/machine.slice
    - /etc/systemd/system/ceph-osd@.service.d/cputuning.conf
  register: systemd
  ignore_errors: yes

- name: reload systemd to apply changes
  command: systemctl daemon-reload
  when: systemd.changed
