---
debian_main_repository: http://debian.mirror.rafal.ca/debian
debian_security_repository: http://security.debian.org

debian_pvc_repository: https://repo.parallelvirtualcluster.org/debian
debian_pvc_signing_key_path: https://repo.parallelvirtualcluster.org/debian/pvc.pub
debian_pvc_signing_key_id: 83D07192314835D4

recursive_dns_servers:
  - 8.8.8.8
  - 8.8.4.4
recursive_dns_search_domains:
  - "{{ local_domain }}"

ntp_servers:
  - time.nrc.ca
  - time.chu.nrc.ca

grub_cmdline: "console=tty0 console=ttyS{{ grub.serial_console[cluster_hardware].console }},115200 plymouth.ignore-serial-consoles splash"
grub_serial: "serial --unit={{ grub.serial_console[cluster_hardware].console }} --speed=115200"

deploy_username: "deploy"

fail2ban_ignorelist:
  - 10.0.0.0/8

cpu_governor: "ondemand"

enable_prometheus_exporter: yes
