---
# Ceph storage
pvc_ceph_storage_secret_uuid: "6e1f4969-f7ea-4be1-9232-e67ce3bfc37e"
pvc_ceph_storage_secret_key: "AQC8y6tWkfUEKxAAI9XKcXlN38Nzbrom899rJw=="
# Database
pvc_dns_database_name: "pvcdns"
pvc_dns_database_user: "pvcdns"
pvc_dns_database_password: "PVCdnsPassw0rd"
pvc_replication_database_user: "replicator"
pvc_replication_database_password: "PVCreplicatorPassw0rd"
pvc_superuser_database_user: "postgres"
pvc_superuser_database_password: "PVCpostgresPassw0rd"
# Coordinators
pvc_nodes:
  - hostname: "pvchv1"
    is_coordinator: yes
    node_id: 1
    router_id: "{{ blsecluster_pvc_clustersubnetsnip }}.1"
    cluster_ip: "by-id"
    storage_ip: "{{ blsecluster_pvc_storagesubnetsnip }}.25/24"
    upstream_ip: "{{ blsecluster_pvc_upstreamsubnetsnip }}.25/24"
    ipmi_host: "hv1-lom.{{ blsedomains_mgmtdomain }}"
    ipmi_user: "{{ username_ipmi_host }}"
    ipmi_password: "{{ passwd_ipmi_host }}"
  - hostname: "pvchv2"
    is_coordinator: yes
    node_id: 2
    router_id: "{{ blsecluster_pvc_clustersubnetsnip }}.2"
    cluster_ip: "by-id"
    storage_ip: "{{ blsecluster_pvc_storagesubnetsnip }}.26/24"
    upstream_ip: "{{ blsecluster_pvc_upstreamsubnetsnip }}.26/24"
    ipmi_host: "hv2-lom.{{ blsedomains_mgmtdomain }}"
    ipmi_user: "{{ username_ipmi_host }}"
    ipmi_password: "{{ passwd_ipmi_host }}"
  - hostname: "pvchv3"
    is_coordinator: yes
    node_id: 3
    router_id: "{{ blsecluster_pvc_clustersubnetsnip }}.3"
    cluster_ip: "by-id"
    storage_ip: "{{ blsecluster_pvc_storagesubnetsnip }}.27/24"
    upstream_ip: "{{ blsecluster_pvc_upstreamsubnetsnip }}.27/24"
    ipmi_host: "hv3-lom.{{ blsedomains_mgmtdomain }}"
    ipmi_user: "{{ username_ipmi_host }}"
    ipmi_password: "{{ passwd_ipmi_host }}"
# Networks
pvc_asn: "{{ blsecluster_pvc_asn }}"
pvc_routers:
  - "{{ blsecluster_pvc_upstreamsubnetsnip }}.2"
  - "{{ blsecluster_pvc_upstreamsubnetsnip }}.3"
pvc_cluster_device: "bond0"
pvc_cluster_domain: "{{ blsedomains_pvc_clusterdomain }}"
pvc_cluster_subnet: "{{ blsecluster_pvc_clustersubnetv4 }}"
pvc_cluster_floatingip: "{{ blsecluster_pvc_clustersubnetsnip }}.252/24"
pvc_storage_device: "vlan99"
pvc_storage_domain: "{{ blsedomains_pvc_storagedomain }}"
pvc_storage_subnet: "{{ blsecluster_pvc_storagesubnetv4 }}"
pvc_storage_floatingip: "{{ blsecluster_pvc_storagesubnetsnip }}.252/24"
pvc_upstream_device: "vlan100"
pvc_upstream_domain: "{{ blsedomains_pvc_upstreamdomain }}"
pvc_upstream_subnet: "{{ blsecluster_pvc_upstreamsubnetv4 }}"
pvc_upstream_floatingip: "{{ blsecluster_pvc_upstreamsubnetsnip }}.252/24"
pvc_upstream_gatewayip: "{{ blsecluster_pvc_upstreamsubnetsnip }}.1"
