---
- name: bring up upstream interface
  command: ifup {{ pvc_upstream_device }}

- name: bring up cluster interface
  command: ifup {{ pvc_cluster_device }}

- name: brindg up storage interface
  command: ifup {{ pvc_storage_device }}

- name: create cluster bridge interface
  command: brctl addbr brcluster
  ignore_errors: yes

- name: add underlying interface to bridge
  command: brctl addif brcluster {{ pvc_cluster_device }}
  ignore_errors: yes

- name: set brcluster up
  command: ip link set brcluster up
  ignore_errors: yes

- name: add IP addresses to upstream interfaces
  command: ip address add {% for node in pvc_nodes if node.hostname == ansible_hostname %}{{ node.upstream_ip }}/{{ pvc_upstream_netmask }}{% endfor %} dev {{ pvc_upstream_device }}
  ignore_errors: yes

- name: add IP addresses to cluster interfaces
  command: ip address add {% for node in pvc_nodes if node.hostname == ansible_hostname %}{{ node.cluster_ip }}/{{ pvc_cluster_netmask }}{% endfor %} dev brcluster
  ignore_errors: yes

- name: add IP addresses to storage interfaces
  command: ip address add {% for node in pvc_nodes if node.hostname == ansible_hostname %}{{ node.storage_ip }}/{{ pvc_storage_netmask }}{% endfor %} dev {{ pvc_storage_device }}
  ignore_errors: yes
