---
# General blacklisting of modules
- name: add module blacklist
  template:
    src: system/blacklist.j2
    dest: /etc/modprobe.d/blacklist.conf

# Logrotate configuration
- name: add logrotate configuration
  template:
    src: system/pvc.j2
    dest: /etc/logrotate.d/pvc

- meta: flush_handlers
